services:
  wordpress:
    image: wordpress:latest
    container_name: euca-estudio
    domainname: euca-estudio.com
    hostname: euca-estudio.com
    build: .
    ports:
      - '3000:3000'
    restart: always
    volumes: ['./wordpress:/var/www/html/clients/euca-estudio']
    env_file:
      - ./.env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.react.rule=Host(`euca-estudio.com`, `www.euca-estudio.com`)'
      - 'traefik.http.routers.react.entrypoints=websecure'
      - 'traefik.http.routers.react.tls.certresolver=myresolver'
    environment:
      PORT: 3000
      WORDPRESS_DB_NAME: silvermica
      WORDPRESS_DB_USER: sylv3rrrrrrmik41
      WORDPRESS_DB_PASSWORD: yPbUGI4Q6UsdmGc8oypJoqSJWmEnpJCgpWJ+40J6Hi9RedMmu9mxOHV1beJshbVPthI
      WORDPRESS_DB_HOST: db:3306

networks:
  default:
    # Use a custom driver
    name: dan1d_network
    driver: bridge
