services:
  wordpress:
    image: wordpress:latest
    container_name: euca-estudio
    domainname: euca-estudio.com
    hostname: euca-estudio.com
    build: .
    ports:
      - '8001:3000'
    restart: always
    volumes: ['./wordpress:/var/www/html/clients/euca-estudio']
    env_file:
      - ./.env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.react.rule=Host(`euca-estudio.com`, `www.euca-estudio.com`)'
      - 'traefik.http.routers.react.entrypoints=websecure'
      - 'traefik.http.routers.react.tls.certresolver=myresolver'
    environment:
      VIRTUAL_HOST: www.euca-estudio.com, euca-estudio.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: www.euca-estudio.com, euca-estudio.com
      LETSENCRYPT_EMAIL: danielfromarg@gmail.com 

networks:
  default:
    # Use a custom driver
    name: dan1d_network
    driver: bridge
