services:
  wordpress:
    image: wordpress:latest
    container_name: euca-estudio
    domainname: euca-estudio.com
    hostname: euca-estudio.com
    build: .
    ports:
      - '8001:80'
    restart: always
    volumes: ['./wordpress:/var/www/html/clients/euca-estudio']
    env_file:
      - ./.env
    environment:
      VIRTUAL_HOST: euca-estudio.com, www.euca-estudio.com
      VIRTUAL_PORT: 8001
      LETSENCRYPT_HOST: www.euca-estudio.com, euca-estudio.com
      LETSENCRYPT_EMAIL: danielfromarg@gmail.com 

networks:
  default:
    external:
      name: nginx-proxy
