version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    image: wordpress:latest
    container_name: euca-estudio
    domainname: euca-estudio.com
    hostname: euca-estudio
    build: .
    ports:
      - '8001:80'
    restart: always
    volumes: ['./wordpress:/var/www/html/clients/euca-estudio']
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  wordpress:
  dbdata:

networks:
  default:
    # Use a custom driver
    name: dan1d_network
    driver: bridge
