version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`euca-estudio.com`, `www.euca-estudio.com`)"
      - "traefik.http.routers.api.entrypoints=websecure,ws,wss"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
    depends_on: 
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - 3000:80
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
  dbdata:

networks:
  default:
    # Use a custom driver
    name: dan1d_network
    driver: bridge
