services:
  wordpress:
    image: wordpress:latest
    container_name: euca-estudio
    domainname: localhost
    hostname: localhost
    build: .
    ports:
      - '8001:80'
    restart: always
    volumes: ['./wordpress:/var/www/html/clients/euca-estudio']
    env_file:
      - ./.env
    environment:
      VIRTUAL_HOST: euca-estudio.dan1d.dev, www.euca-estudio.dan1d.dev
      VIRTUAL_PORT: 8001
      LETSENCRYPT_HOST: www.euca-estudio.dan1d.dev, euca-estudio.dan1d.dev
      LETSENCRYPT_EMAIL: danielfromarg@gmail.com 

networks:
  default:
    external:
      name: nginx-proxy